name: presence2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cloud_firestore: 4.3.1
  cupertino_icons: ^1.0.2
  firebase_auth: 4.2.5
  firebase_core: 2.4.1
  firebase_storage: 11.0.10
  get: ^4.6.5
  image_picker: 0.8.6
  convex_bottom_bar: 3.1.0+1
  intl: 0.17.0
  geolocator: 9.0.2
  geocoding: 2.0.5
  syncfusion_flutter_datepicker: 20.4.44
  flutter:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
